"""Added karma to user

Revision ID: 04329d7e7e31
Revises: 2e21cd7ecbc7
Create Date: 2023-06-21 01:09:13.163230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04329d7e7e31'
down_revision = '2e21cd7ecbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('karma', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('karma')

    # ### end Alembic commands ###
