"""empty message

Revision ID: 53df43122f06
Revises: f56748760a5c
Create Date: 2023-06-17 02:13:09.928927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53df43122f06'
down_revision = 'f56748760a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_joined', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('date_joined')

    # ### end Alembic commands ###
