"""Added value field to Vote model

Revision ID: 6e7a3d29f64a
Revises: 72a92d25570e
Create Date: 2023-06-19 15:25:08.918100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e7a3d29f64a'
down_revision = '72a92d25570e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.Integer(), nullable=False))
        batch_op.drop_column('vote')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vote', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('value')

    # ### end Alembic commands ###
