"""Add is_deleted column to posts table

Revision ID: d1fa95fb151d
Revises: 8099e7fe3a62
Create Date: 2023-07-11 10:03:00.664435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fa95fb151d'
down_revision = '8099e7fe3a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.alter_column('post_type',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('post_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
