"""Communities table

Revision ID: daa33c19d397
Revises: f741c4b6f93d
Create Date: 2023-06-17 14:13:45.676973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daa33c19d397'
down_revision = 'f741c4b6f93d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('community_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
