"""Add votes column to posts table

Revision ID: dde782d264aa
Revises: e25ff40cb17e
Create Date: 2023-06-28 10:55:58.493647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde782d264aa'
down_revision = 'e25ff40cb17e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('votes', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
